// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'groupBlock': string;
  'index': string;
  'p404': string;
  'root': string;
  'titleText': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
